name: Fly CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # test:
  #   name: Build and test
  #   runs-on: ubuntu-latest
  #   # env:
  #   #   DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
  #   #   DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASS }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     # - name: Login to Docker Hub
  #     #   run: docker login -u $DOCKER_USER -p $DOCKER_PASS

  #     - name: Build image
  #       run: docker build -f Dockerfile.dev -t bnc-attendance:test .

  #     - name: Run tests
  #       run: docker run bnc-attendance:test yarn test --detectOpenHandles --runInBand
  deploy:
    name: Deploy app
    # needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.3
        with:
          args: 'deploy'
